name: AI-Prod Deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  push:
    branches:
      - 'ai-prod/**'
      - main
    paths:
      - 'src/**'

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Comprehensive checks
        run: |
          npm run lint
          npm run type-check
          npm run test:unit
          npm run test:integration
          npm run test:e2e
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  security-review:
    needs: validate-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Security scan
        run: npm run security:full
      - name: Dependency scan
        run: npm audit --production --audit-level=moderate
      - name: License compliance check
        run: npm run license:check

  deploy-staging:
    needs: [validate-and-build, security-review]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment"
          npm run deploy:staging
      - name: Run smoke tests
        run: npm run test:smoke

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          npm run deploy:production
      - name: Verify deployment
        run: |
          echo "Verifying production deployment"
          npm run verify:deployment 