name: AI-Review Comprehensive Checks

on:
  pull_request:
    branches:
      - 'ai-review/**'
  push:
    branches:
      - 'ai-review/**'

jobs:
  comprehensive-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run type-check
      - name: Unit tests
        run: npm run test:unit
      - name: Integration tests
        run: npm run test:integration
      - name: Coverage report
        run: npm run test:coverage
      - name: Check coverage thresholds
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Coverage $COVERAGE% is below the required threshold of 80%"
            exit 1
          fi
      - name: Comprehensive security scan
        run: npm run security:full
      - name: Dependency audit
        run: npm audit --production
      - name: Performance benchmark
        run: npm run benchmark
      - name: Documentation check
        run: npm run docs:check 